import type { Theme } from '../theme'
import { THEME_SCHEMA_VERSION } from '../theme'

/** One Light — the Atom-derived light counterpart to One Dark. */
export const oneLight: Theme = {
  version: THEME_SCHEMA_VERSION,
  id: 'one-light',
  name: 'One Light',
  type: 'light',
  builtIn: true,
  author: 'Orquestra theme pack',
  bootBackground: '#fafafa',
  app: {
    'surface-0': '#fafafa',
    'surface-1': '#f0f0f1',
    'surface-2': '#eaeaeb',
    'surface-3': '#e5e5e6',
    'surface-4': '#dbdbdc',
    'surface-5': '#d0d0d1',
    'surface-6': '#c6c6c7',
    'titlebar-bg': '#e7e7e8',
    'canvas-bg': '#f4f4f4',
    'canvas-bg-alt': '#eeeeef',
    'grid-dot': '#e0e0e1',
    'grid-line': '#ebebec',
    'border-subtle': '#e1e1e2',
    'border-strong': '#c9c9ca',
    'border-focus': '#4078f2',
    'text-primary': '#383a42',
    'text-secondary': '#4f525e',
    'text-muted': '#a0a1a7',
    'text-inverse': '#fafafa',
    'focus-blue': '#4078f2',
    'activity-green': '#50a14f',
    'activity-orange': '#c18401',
    'shadow-node': 'rgba(0,0,0,0.10)',
    'shadow-node-focused': 'rgba(64,120,242,0.30)',
    'node-bg-active': '#ffffff',
    'node-dim-overlay': 'rgba(250,250,250,0.55)',
    'scrollbar-thumb': '#b0b0b066',
    'scrollbar-thumb-hover': '#9a9a9a99',
    'surface-hover': '#ececed',
    'surface-hover-strong': '#e3e3e4',
    'git-added': '#50a14f',
    'git-modified': '#c18401',
    'git-deleted': '#e45649',
    'git-untracked': '#50a14f',
    'git-renamed': '#4078f2',
    'agent-rgb': '64 120 242',
    'agent-light-rgb': '97 145 245',
  },
  terminal: {
    background: '#fafafa',
    foreground: '#383a42',
    cursor: '#526fff',
    selectionBackground: '#dbdbdc',
    black: '#383a42', red: '#e45649', green: '#50a14f', yellow: '#c18401',
    blue: '#4078f2', magenta: '#a626a4', cyan: '#0184bc', white: '#a0a1a7',
    brightBlack: '#696c77', brightRed: '#e45649', brightGreen: '#50a14f', brightYellow: '#986801',
    brightBlue: '#4078f2', brightMagenta: '#a626a4', brightCyan: '#0184bc', brightWhite: '#2c2e36',
  },
  editor: {
    base: 'vs',
    colors: {
      'editor.background': '#fafafa',
      'editor.foreground': '#383a42',
      'editor.selectionBackground': '#dbdbdc',
      'editor.lineHighlightBackground': '#f0f0f1',
      'editorCursor.foreground': '#526fff',
      'editorLineNumber.foreground': '#9d9d9f',
      'editorLineNumber.activeForeground': '#383a42',
    },
    tokens: [
      { token: 'comment', foreground: 'a0a1a7', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'a626a4' },
      { token: 'keyword.control', foreground: 'a626a4' },
      { token: 'storage', foreground: 'a626a4' },
      { token: 'storage.type', foreground: 'a626a4' },
      { token: 'string', foreground: '50a14f' },
      { token: 'constant.numeric', foreground: '986801' },
      { token: 'constant.language', foreground: '986801' },
      { token: 'constant', foreground: '0184bc' },
      { token: 'variable', foreground: 'e45649' },
      { token: 'variable.parameter', foreground: '383a42' },
      { token: 'type', foreground: 'c18401' },
      { token: 'entity.name.type', foreground: 'c18401' },
      { token: 'entity.name.class', foreground: 'c18401' },
      { token: 'entity.name.function', foreground: '4078f2' },
      { token: 'support.function', foreground: '4078f2' },
      { token: 'entity.name.tag', foreground: 'e45649' },
      { token: 'entity.other.attribute-name', foreground: '986801' },
      { token: 'operator', foreground: '0184bc' },
    ],
  },
}
