import type { Theme } from '../theme'
import { THEME_SCHEMA_VERSION } from '../theme'

/** Visual Studio Dark — Microsoft's classic Dark+ editor palette. */
export const visualStudioDark: Theme = {
  version: THEME_SCHEMA_VERSION,
  id: 'visual-studio-dark',
  name: 'Visual Studio Dark',
  type: 'dark',
  builtIn: true,
  author: 'Orquestra theme pack',
  bootBackground: '#1e1e1e',
  app: {
    'surface-0': '#1e1e1e',
    'surface-1': '#252526',
    'surface-2': '#2d2d2d',
    'surface-3': '#333333',
    'surface-4': '#3c3c3c',
    'surface-5': '#424242',
    'surface-6': '#4e4e4e',
    'titlebar-bg': '#3c3c3c',
    'canvas-bg': '#181818',
    'canvas-bg-alt': '#202020',
    'grid-dot': '#2a2a2a',
    'grid-line': '#262626',
    'border-subtle': '#2b2b2b',
    'border-strong': '#454545',
    'border-focus': '#007acc',
    'text-primary': '#d4d4d4',
    'text-secondary': '#cccccc',
    'text-muted': '#858585',
    'text-inverse': '#1e1e1e',
    'focus-blue': '#007acc',
    'activity-green': '#4ec9b0',
    'activity-orange': '#ce9178',
    'shadow-node': 'rgba(0,0,0,0.45)',
    'shadow-node-focused': 'rgba(0,122,204,0.40)',
    'node-bg-active': '#252526',
    'node-dim-overlay': 'rgba(0,0,0,0.45)',
    'scrollbar-thumb': '#79797966',
    'scrollbar-thumb-hover': '#79797999',
    'surface-hover': '#2a2d2e',
    'surface-hover-strong': '#37373d',
    'git-added': '#81b88b',
    'git-modified': '#e2c08d',
    'git-deleted': '#f48771',
    'git-untracked': '#73c991',
    'git-renamed': '#4ec9b0',
    'agent-rgb': '0 122 204',
    'agent-light-rgb': '62 148 222',
  },
  terminal: {
    background: '#1e1e1e',
    foreground: '#cccccc',
    cursor: '#d4d4d4',
    selectionBackground: '#264f78',
    black: '#000000', red: '#cd3131', green: '#0dbc79', yellow: '#e5e510',
    blue: '#2472c8', magenta: '#bc3fbc', cyan: '#11a8cd', white: '#e5e5e5',
    brightBlack: '#666666', brightRed: '#f14c4c', brightGreen: '#23d18b', brightYellow: '#f5f543',
    brightBlue: '#3b8eea', brightMagenta: '#d670d6', brightCyan: '#29b8db', brightWhite: '#ffffff',
  },
  editor: {
    base: 'vs-dark',
    colors: {
      'editor.background': '#1e1e1e',
      'editor.foreground': '#d4d4d4',
      'editor.selectionBackground': '#264f78',
      'editor.lineHighlightBackground': '#2a2a2a',
      'editorCursor.foreground': '#aeafad',
      'editorLineNumber.foreground': '#858585',
      'editorLineNumber.activeForeground': '#c6c6c6',
    },
    tokens: [
      { token: 'comment', foreground: '6a9955', fontStyle: 'italic' },
      { token: 'keyword', foreground: '569cd6' },
      { token: 'keyword.control', foreground: 'c586c0' },
      { token: 'storage', foreground: '569cd6' },
      { token: 'storage.type', foreground: '569cd6' },
      { token: 'string', foreground: 'ce9178' },
      { token: 'constant.numeric', foreground: 'b5cea8' },
      { token: 'constant.language', foreground: '569cd6' },
      { token: 'constant', foreground: '4fc1ff' },
      { token: 'variable', foreground: '9cdcfe' },
      { token: 'variable.parameter', foreground: '9cdcfe' },
      { token: 'type', foreground: '4ec9b0' },
      { token: 'entity.name.type', foreground: '4ec9b0' },
      { token: 'entity.name.class', foreground: '4ec9b0' },
      { token: 'entity.name.function', foreground: 'dcdcaa' },
      { token: 'support.function', foreground: 'dcdcaa' },
      { token: 'entity.name.tag', foreground: '569cd6' },
      { token: 'entity.other.attribute-name', foreground: '9cdcfe' },
      { token: 'operator', foreground: 'd4d4d4' },
    ],
  },
}
