import type { Theme } from '../theme'
import { THEME_SCHEMA_VERSION } from '../theme'

/** Visual Studio Light — Microsoft's classic light editor palette. */
export const visualStudioLight: Theme = {
  version: THEME_SCHEMA_VERSION,
  id: 'visual-studio-light',
  name: 'Visual Studio Light',
  type: 'light',
  builtIn: true,
  author: 'Orquestra theme pack',
  bootBackground: '#ffffff',
  app: {
    'surface-0': '#ffffff',
    'surface-1': '#f3f3f3',
    'surface-2': '#ececec',
    'surface-3': '#e4e4e4',
    'surface-4': '#dddddd',
    'surface-5': '#d4d4d4',
    'surface-6': '#cbcbcb',
    'titlebar-bg': '#dddddd',
    'canvas-bg': '#f8f8f8',
    'canvas-bg-alt': '#f1f1f1',
    'grid-dot': '#dedede',
    'grid-line': '#ececec',
    'border-subtle': '#e7e7e7',
    'border-strong': '#cecece',
    'border-focus': '#005fb8',
    'text-primary': '#1f1f1f',
    'text-secondary': '#3b3b3b',
    'text-muted': '#6e6e6e',
    'text-inverse': '#ffffff',
    'focus-blue': '#005fb8',
    'activity-green': '#388a34',
    'activity-orange': '#bf8803',
    'shadow-node': 'rgba(0,0,0,0.10)',
    'shadow-node-focused': 'rgba(0,95,184,0.30)',
    'node-bg-active': '#ffffff',
    'node-dim-overlay': 'rgba(255,255,255,0.55)',
    'scrollbar-thumb': '#64646466',
    'scrollbar-thumb-hover': '#64646499',
    'surface-hover': '#e8e8e8',
    'surface-hover-strong': '#dedede',
    'git-added': '#587c0c',
    'git-modified': '#895503',
    'git-deleted': '#ad0707',
    'git-untracked': '#388a34',
    'git-renamed': '#005fb8',
    'agent-rgb': '0 95 184',
    'agent-light-rgb': '0 120 212',
  },
  terminal: {
    background: '#ffffff',
    foreground: '#3b3b3b',
    cursor: '#005fb8',
    selectionBackground: '#add6ff',
    black: '#000000', red: '#cd3131', green: '#00bc00', yellow: '#949800',
    blue: '#0451a5', magenta: '#bc05bc', cyan: '#0598bc', white: '#555555',
    brightBlack: '#666666', brightRed: '#cd3131', brightGreen: '#14ce14', brightYellow: '#b5ba00',
    brightBlue: '#0451a5', brightMagenta: '#bc05bc', brightCyan: '#0598bc', brightWhite: '#a5a5a5',
  },
  editor: {
    base: 'vs',
    colors: {
      'editor.background': '#ffffff',
      'editor.foreground': '#000000',
      'editor.selectionBackground': '#add6ff',
      'editor.lineHighlightBackground': '#f3f3f3',
      'editorCursor.foreground': '#005fb8',
      'editorLineNumber.foreground': '#6e7681',
      'editorLineNumber.activeForeground': '#1f1f1f',
    },
    tokens: [
      { token: 'comment', foreground: '008000', fontStyle: 'italic' },
      { token: 'keyword', foreground: '0000ff' },
      { token: 'keyword.control', foreground: 'af00db' },
      { token: 'storage', foreground: '0000ff' },
      { token: 'storage.type', foreground: '0000ff' },
      { token: 'string', foreground: 'a31515' },
      { token: 'constant.numeric', foreground: '098658' },
      { token: 'constant.language', foreground: '0000ff' },
      { token: 'constant', foreground: '0070c1' },
      { token: 'variable', foreground: '001080' },
      { token: 'variable.parameter', foreground: '001080' },
      { token: 'type', foreground: '267f99' },
      { token: 'entity.name.type', foreground: '267f99' },
      { token: 'entity.name.class', foreground: '267f99' },
      { token: 'entity.name.function', foreground: '795e26' },
      { token: 'support.function', foreground: '795e26' },
      { token: 'entity.name.tag', foreground: '800000' },
      { token: 'entity.other.attribute-name', foreground: 'e50000' },
      { token: 'operator', foreground: '000000' },
    ],
  },
}
